### ISSUE TITLE
Add support for core's Basic Auth module

### ISSUE THREAD

**Issue by JohnAlbin** [drupal-graphql/graphql#765] opened 2019-04-11 20:12 UTC
This is a dupe of the closed https://github.com/drupal-graphql/graphql/issues/578

However, I've tested this and core Basic Auth module doesn't work with the GraphQL module. 

On my test site, I installed GraphQL and BasicAuth modules and used the "admin" user and password in the `Authorization: Basic [base64 of user:password]` header. And I know the authentication HTTP header is working properly.

When I try a GraphQL query with that HTTP header, I see 2 things happen:
1. The response is not a JSON response, but a HTML error page.
2. Drupal watchdog logs an error for the user "admin" and path `/graphql` saying Access denied. Since it shows the "admin" user, I know the HTTP header is working. If I remove the header, I see a similar watchdog message, but the user is "anonymous".

<img width="898" alt="Screen Shot 2019-04-11 at 13 02 15" src="https://user-images.githubusercontent.com/33429/55989722-d1e88780-5c5a-11e9-800b-d906f8a36a47.png">

The [docs for basic auth](https://www.drupal.org/docs/8/core/modules/basic_auth/overview)  say that the module does NOT provide basic auth for ALL pages. It only provides authentication for those routes that are configured to allow basic auth. And the `/graphql` route doesn't have it configured.

Which is why GraphQL module + Basic Auth module aren't working together.

**Comment by JohnAlbin** [comment] 2019-04-11 20:26
BTW, I'm doing this on a Gatsby static build of a Drupal site, which basic auth is easy and secure enough (if connecting over SSL.)

**Comment by ArneSaknussemm89** [comment] 2019-04-11 22:04
I'm having the same issue using:

https://www.drupal.org/project/graphql_jwt
https://www.drupal.org/project/jwt
https://www.drupal.org/project/keys

but it doesn't seem like the GraphQL route gives you an option of what "Authentication" method to follow. So when supplying an Auth header using either basic_auth or jwt (Basic or Bearer headers) it denies the request no matter what.

I'm assuming someone would need to use a RouteSubscriber and alter the routes to use whatever Authentication methodology is desired.

Thinking of something like https://www.drupal.org/node/2122195 to then "hand off" auth to needed checks based on config.

Could also be overcomplicating it, and perhaps this is the better route (a developer manually overriding the routes with desired auth).

**Comment by blazeyo** [comment] 2019-04-12 17:14
According to https://www.drupal.org/docs/8/api/routing-system/structure-of-routes

> _auth: The default authentication manager (Ex: _auth: ['basic_auth', 'cookie'] ) that enables developers **to limit** the set of allowed authentication mechanisms to the route.

It turns out that is not the case though. A route needs to have the `_auth` option set in order to use the additional auth providers. The code that checks it is [here](https://git.drupalcode.org/project/drupal/blob/8.8.x/core/lib/Drupal/Core/Authentication/AuthenticationManager.php#L175).

Steps to reproduce the issue:

- withdraw the execute arbitrary queries permission from the anonymous user
(optional) set a breakpoint here https://git.drupalcode.org/project/drupal/blob/8.8.x/core/lib/Drupal/Core/Authentication/AuthenticationManager.php#L175
- run curl --user user:password http://site.url/graphql?XDEBUG_SESSION_START=PHPSTORM
- visit /admin/reports/dblog

The changes in #766 fix the issue for me.

**Comment by pmelab** [comment] 2019-04-13 05:27
Hey guys! Thank you for solving this so fast! I planned to look at it during the weekend, but its already resolved :)

With #766 merged we what core provides, and thats sufficient i think. For other authentication providers altering the route is probably the way to go.

**Closed as completed by pmelab** 2019-04-13 05:27 UTC
