### ISSUE TITLE
The query result yielded cache contexts Error is thrown when tmgmt_content is enabled.

### ISSUE THREAD

**Issue by awm086** [drupal-graphql/graphql#585] opened 2018-04-25 21:45 UTC
graphql module checks for CacheContexts when queries are submitted :
```
if ($missing = array_diff($result->getCacheContexts(), $metadata->getCacheContexts())) {
        throw new \LogicException(sprintf(
          'The query result yielded cache contexts (%s) that were not part of the static query analysis.',
          implode(', ', $missing)
        ));
      }
```
And as soon as I enabled tgmgt_content, the exception above is thrown upon the execution of graphql query. It complains that a cache context "(url.query_args:key)" is missing. This context is being added by tmgmt_content_entity_access in :
```
/**
 * Implements hook_entity_access().
 */
function tmgmt_content_entity_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {

    .....
  return $result->addCacheContexts(['url.query_args:key']);
}
```
commenting out return $result->addCacheContexts(['url.query_args:key']); fixes the issue.
But it seems that tmgmt_content_entity_access is adding the cache context appropriately. And I believe this is may be a graphQl issue. 
To Reproduce:
- enable graphql
- enable tgmgt_content
- grant anonymous users to execute graphql queries
- Execute any graph ql query as anonymous user.

**Comment by pmelab** [comment] 2018-04-26 06:42
This is a duplicate of #584

**Closed as completed by pmelab** 2018-04-26 06:42 UTC
