### ISSUE TITLE
Schema Showing fields that don't belong to an Entity

### ISSUE THREAD

**Issue by naitschi** [drupal-graphql/graphql#638] opened 2018-07-20 08:40 UTC
Hello,
This Problem is showing up in Verison **3.0-beta-8** and **3.x-dev**.

When I write a Query there are fields shown that don't belongt to the requested Entity.

![graphql](https://user-images.githubusercontent.com/12916150/42992572-35310bfa-8c09-11e8-8d42-0d4c70b8040e.PNG)

These Fields don't belong there.

How can I fix this Problem?

**Comment by pmelab** [comment] 2018-07-23 11:45
This is a duplicate of #615 .

**Closed as completed by pmelab** 2018-07-23 11:45 UTC
