### ISSUE TITLE
Regression: cache dependencies are not retrieved

### ISSUE THREAD

**Issue by peterkeppert** [drupal-graphql/graphql#226] opened 2017-08-03 14:44 UTC
Steps to reproduce:
1. run a GraphQL query retrieving e.g. _entityById_
2. update the entity title
3. run the same GraphQL again

Result: GraphQL query returns the _old_ title
Expected: GraphQL query returns the _new_ title

Issue is specifically caused by appropriate cache tags not being added to _cache_graphql_response_ table (_entity_type:entity_id_ cache tags (e.g. _node:1_) are missing from the _tags_ column). This regression seems to have been introduced with https://github.com/fubhy/graphql-drupal/commit/3d76582094e456a5a16cd2f0f1130ddc5f6ee6cb

**Comment by shipiak** [comment] 2017-08-04 08:24
Upvoting this issue.
I think we're experiencing same problem with cache.

**Comment by fubhy** [comment] 2017-08-04 08:31
Will look into it. Btw. to upvote you can also just +1 with emoji ;)

**Comment by fubhy** [comment] 2017-08-04 08:50
Should be fixed with https://github.com/fubhy/graphql-drupal/pull/228

**Closed as completed** 2017-08-04 09:10 UTC

**Comment by fubhy** [comment] 2017-08-04 09:11
I merged the fix and published it on drupal.org / composer. Please test and validate with the latest 8.x.-3.x-dev. If it works, I'll publish a new alpha with the fix included.

**Comment by peterkeppert** [comment] 2017-08-04 09:46
Hi @fubhy, tested and confirmed working, thanks for a fast fix :)

**Comment by wimleers** [comment] 2017-08-09 18:01
I'm … surprised … to learn that A) there is no test coverage for this, B) this was fixed without regression test coverage.

What @peterkeppert reported as the bug is literally the most basic way you could use cache tags. I remember working with you, @fubhy, on GraphQL + cache tags + cache contexts. So this issue single-handedly makes me quite skeptical about the state of the GraphQL module…

**Comment by weitzman** [comment] 2017-08-09 19:20
I think thats a bit harsh. This project has come a long way recently, with schema generation based on entity info, views integration, .... Functionally, this project is quite impressive.

 Its true that the test methodology is not up to core standards but virtually no contrib meets that standard.

**Comment by fubhy** [comment] 2017-08-09 19:36
I am also surprised by your comment, Wim. We do have test coverage for caching but it did not catch this case because dynamic cache tags are currently not tested. There is an open issue to improve test coverage for this scenario. After discussing it with @pmelab we agreed that we will work oj improved test coverage within that issue instead of here.

I dont remember working with you on caching in graphql at all by the way. I remember tagging you in that issue to get your feedback but I believe we never sat down together to talk it through. In the end, however I built it on my own. If you want to get involved now I'd be happy to get your feedback nonetheless.

**Comment by fubhy** [comment] 2017-08-09 19:39
I'd love to see you give graphql a serious testrun btw. So far I've only seen unfounded scepticism like this comment here. GraphQL and this module are definitly prime time ready. We are using it successfuly for quite some time now. Let me know once you are ready to give it a testspin

**Comment by pmelab** [comment] 2017-08-10 03:55
> So this issue single-handedly makes me quite skeptical about the state of the GraphQL module…

Skeptical if it deserves the "alpha" state it's currently tagged with? Which literally says "adding features and tests"? Or are you questioning the competence of it's contributors?
A lot of people see a great opportunity for Drupal here and are working hard to pull this off (unfunded btw), and comments without constructive criticism or advice but scattered with menacing ellipsis don't help.

**Comment by pmelab** [comment] 2017-08-10 03:56
> GraphQL and this module are definitly prime time ready.

I'm not 100% sure what "prime time" means. Are we going to be on TV? I've got to tell my mother.

**Comment by fubhy** [comment] 2017-08-25 15:03
@wimleers btw, we've got 65% code coverage. Yes, we still need to improve on that but I just wanted to outline that our code coverage is certainly higher (much higher) than the vast majority of Drupal modules available. ;)
