### ISSUE TITLE
Config entities

### ISSUE THREAD

**Issue by blazeyo** [drupal-graphql/graphql#387] opened 2017-10-15 21:17 UTC
How should we handle configuration entities and references to such (e.g. node type, user roles, etc)? Right now it's only possible to get the id via the `target_id` property of the reference field.

**Comment by fubhy** [comment] 2017-10-16 07:37
Well we definitely do want to expose config entities. @peterkeppert started a PR here https://github.com/fubhy/graphql-drupal/pull/299

But it does not expose any config values. Just the config entity properties. That would need to be added. Do you want to work on that?

**Comment by blazeyo** [comment] 2017-10-16 07:40
Sure. Do you think #299 is ready to merge?

**Comment by fubhy** [comment] 2017-10-16 07:44
I'd prefer to first finish the full PR (including config values) and then review it as a whole. You can start off of #299 though.

**Comment by fubhy** [comment] 2017-10-17 13:37
Duplicate of #64

**Closed as completed by fubhy** 2017-10-17 13:37 UTC
