### ISSUE TITLE
Explorer page WSOD after webonyx update

### ISSUE THREAD

**Issue by drupov** [drupal-graphql/graphql#546] opened 2018-03-08 22:29 UTC
After installing the latest dev of the module with the webonyx changes already in, the explorer page does not load.

There is an error in the console - see https://ibb.co/m5SAJS:
`Uncaught Error: Comment.entityId expects type "FieldCommentEntityId" but CommentComment.entityId provides type "String".`

**Comment by skp3zl** [comment] 2018-03-09 13:49
Same here. Upgraded from beta5 with composer on a test site with just the default content types (and comment types). Reinstalled graphql and graphql_core. Cleared Drupal cache and browser cache

**Comment by fubhy** [comment] 2018-03-09 16:28
Comments are the issue here. Renaming the "entityId" name of the EntityId plugin to something else fixes it. We will find a way to resolve these name clashes.

**Comment by fubhy** [comment] 2018-03-09 16:29
Here is a more thorough explanation of what's happening: https://github.com/drupal-graphql/graphql/issues/542#issuecomment-371088061

**Comment by pavlosdan** [comment] 2018-03-10 09:33
tried this but it didn't resolve the issue. 
Also getting a different error from drupov in the console:

`drupal.js?v=8.4.5:13 Uncaught TypeError: Cannot read property 'types' of undefined
    at i (bundle.min.js?v=8.4.5:1)
    at Object.attach (bundle.min.js?v=8.4.5:1)
    at Object.Drupal.attachBehaviors (drupal.js?v=8.4.5:25)
    at drupal.init.js?v=8.4.5:16
    at HTMLDocument.t (ready.min.js?v=1.0.8:4)`

**Comment by fubhy** [comment] 2018-03-11 10:44
@pavlosdan that is a different error. my solution only works if you have the "entity_id" / "entityId" error.

**Comment by justinlevi** [comment] 2018-03-12 18:57
@pavlosdan I just upgraded to 8.5 via a composer update and started seeing the same JS error. When I run `drush cr` I get the following: 

```
Invalid argument supplied for foreach() in Drupal\graphql_core\Plugin\Deriver\Types\EntityBundleDeriver-&gt;getDerivativeDefinitions() (line 75 of                  [warning]
modules/contrib/graphql/modules/graphql_core/src/Plugin/Deriver/Types/EntityBundleDeriver.php).
Drupal\graphql_core\Plugin\Deriver\Types\EntityBundleDeriver-&gt;getDerivativeDefinitions(Array) (Line: 101)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator-&gt;getDerivatives(Array) (Line: 87)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator-&gt;getDefinitions() (Line: 284)
Drupal\Core\Plugin\DefaultPluginManager-&gt;findDefinitions() (Line: 175)
Drupal\Core\Plugin\DefaultPluginManager-&gt;getDefinitions() (Line: 139)
Drupal\graphql\Plugin\Deriver\PluggableSchemaDeriver-&gt;Drupal\graphql\Plugin\Deriver\{closure}(Array, &#039;type&#039;)
array_reduce(Array, Object, Array) (Line: 157)
Drupal\graphql\Plugin\Deriver\PluggableSchemaDeriver-&gt;buildTypeMap(Array) (Line: 87)
Drupal\graphql\Plugin\Deriver\PluggableSchemaDeriver-&gt;getDerivativeDefinitions(Array) (Line: 101)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator-&gt;getDerivatives(Array) (Line: 87)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator-&gt;getDefinitions() (Line: 284)
Drupal\Core\Plugin\DefaultPluginManager-&gt;findDefinitions() (Line: 175)
Drupal\Core\Plugin\DefaultPluginManager-&gt;getDefinitions() (Line: 41)
Drupal\graphql\Routing\QueryRoutes-&gt;alterRoutes(Object) (Line: 37)
Drupal\Core\Routing\RouteSubscriberBase-&gt;onAlterRoutes(Object, &#039;routing.route_alter&#039;, Object)
call_user_func(Array, Object, &#039;routing.route_alter&#039;, Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;routing.route_alter&#039;, Object) (Line: 184)
Drupal\Core\Routing\RouteBuilder-&gt;rebuild() (Line: 83)
Drupal\Core\ProxyClass\Routing\RouteBuilder-&gt;rebuild() (Line: 1157)
drupal_flush_all_caches() (Line: 52)
drupal_rebuild(Object, Object) (Line: 302)
drush_cache_rebuild() (Line: 422)
_drush_invoke_hooks(Array, Array) (Line: 231)
drush_command() (Line: 199)
drush_dispatch(Array) (Line: 67)
Drush\Boot\BaseBoot-&gt;bootstrap_and_dispatch() (Line: 66)
drush_main() (Line: 12)

```

**Comment by justinlevi** [comment] 2018-03-12 19:04
To note, I am using the umami distro profile and I'm trying to get the core media module working

Update: Now seems to be working ???

**Comment by pavlosdan** [comment] 2018-03-13 09:21
@justinlevi I was on 8.4.5. Haven't tried with 8.5 yet.

**Comment by skp3zl** [comment] 2018-03-13 19:56
I get a similar error to @pavlosdan after adding a Date Range field.
```
Uncaught TypeError: Cannot read property 'types' of undefined
    at i (bundle.min.js?v=8.5.0:1)
    at Object.attach (bundle.min.js?v=8.5.0:1)
    at js_EhClZlGJJi0vcEOjy5i8ZVGSPlznxMFbQq-VyAIijyg.js:62
    at Array.forEach (<anonymous>)
    at Object.Drupal.attachBehaviors (js_EhClZlGJJi0vcEOjy5i8ZVGSPlznxMFbQq-VyAIijyg.js:59)
    at js_EhClZlGJJi0vcEOjy5i8ZVGSPlznxMFbQq-VyAIijyg.js:244
    at HTMLDocument.t (js_BKcMdIbOMdbTdLn9dkUq3KCJfIKKo2SvKoQ1AnB8D-g.js:4)
```

**Comment by pmelab** [comment] 2018-03-15 13:33
> Uncaught Error: Comment.entityId expects type "FieldCommentEntityId" but CommentComment.entityId provides type "String".

... should be fixed with #556. Is there anything reproduceable left in this issue?

**Comment by fubhy** [comment] 2018-03-15 17:40
Comments work for me now. /cc @drupov

**Closed as completed by fubhy** 2018-03-15 17:40 UTC

**Comment by drupov** [comment] 2018-03-15 20:52
And yes, back it is! Thanks!

**Comment by secmi** [comment] 2018-03-29 13:48
@sebkamil, @pavlosdan Have the same error on 8.5.1, did you find some solution?

**Comment by skp3zl** [comment] 2018-03-29 14:28
@secmi I tried it out again with the latest graphql 3.x-dev (8b362e0) and Drupal 8.5.1; it seems to be working now, at least with date range. Tested it with the same dummy site that was giving me the error before; didn't change anything else. Not sure what was happening unfortunately.

**Comment by pavlosdan** [comment] 2018-04-19 07:39
@secmi I just got around to upgrading. My issue right now is a Logic exception "Fatal error: Uncaught LogicException: Missing type metatag. in /var/www/drupalvm/docroot/modules/contrib/graphql/src/Plugin/GraphQL/Schemas/SchemaPluginBase.php"

Looking into it. I installed graphql_metatag but still getting the same error.

**Comment by emb03** [comment] 2018-09-07 22:28
Graphql Explorer WSOD:
Drupal Version:
8.5.7

GraphQL:
3.0.0-beta8

Javascript error:
js_EhClZlGJJi0vcEOjy5i8ZVGSPlznxMFbQq-VyAIijyg.js:50 Uncaught Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "1400X200_HERO_HALF_IMAGE" does not.

Not sure where "1400X200_HERO_HALF_IMAGE"  is coming a from a image_style, a crop_style or a since deleted view.

**Comment by Melcus** [comment] 2020-08-28 09:19
@pavlosdan did you ever get around this issue ?
