### ISSUE TITLE
Performance Issues with larger schemas

### ISSUE THREAD

**Issue by ayalon** [drupal-graphql/graphql#1312] opened 2022-11-09 14:19 UTC
We built a larger schema with the new module and faced some severe performance issues.

I did several hours profiling and figured out multiple issues, that could easily be improved.

As a starting point, I profiled a fully cached GraphQL request with development mode turned off. This looked like this:

![image](https://user-images.githubusercontent.com/432045/200847650-bcd7d107-6448-4b0b-9a48-c7bac8ee7da9.png)

On every request, the schema is validated by the webonyx library even though it comes from the cache. This can be easily turned off 
**File `SdlSchemaPluginBase::getSchema()`**
```
    $options = ['assumeValid' => true];
    $schema = BuildSchema::build($document, function ($config, TypeDefinitionNode $type) use ($resolver) {
      if ($type instanceof InterfaceTypeDefinitionNode || $type instanceof UnionTypeDefinitionNode) {
        $config['resolveType'] = $resolver;
      }

      return $config;
    }, $options);
```
There is an option `assumeValid` and if passed, the validation is skipped. This saved me approximatly 300ms per request.

Additionally, to support larger ASTs we also had to add the option 'noLocation' to the Parser::parse() function to avoid recursion loops.
This also gives a performance boost because the resulting AST is substantially smaller.
```
protected function getSchemaDocument(array $extensions = []) {

...

    $options = ['noLocation' => TRUE];
    $ast = Parser::parse(implode("\n\n", $schema), $options);
    if (empty($this->inDevelopment)) {
      $this->astCache->set($cid, $ast, CacheBackendInterface::CACHE_PERMANENT, ['graphql']);
    }

...
```
I went a head and figured out, that the performance is still an issue. I think there is a serious flaw in the implementation of the SchemaExtender. Here is a timeline when extending the schema and after fixing the issues above:

![image](https://user-images.githubusercontent.com/432045/200850169-24cc2175-740d-4c25-9953-a3dce12e2611.png)

As we can see, a function is called, named \GraphQL\Type\Schema::getTypeMap(). The method decription looks like this:
```
    /**
     * Returns array of all types in this schema. Keys of this array represent type names, values are instances
     * of corresponding type definitions
     *
     * This operation requires full schema scan. Do not use in production environment.
     *
     * @return array<string, Type>
     *
     * @api
     */
    public function getTypeMap() : array
```
The maintainer warns us, to run this function in production. But we run it on every request if schema extensions are turned on. :-)

Therefore, I implemented a caching of the extended schema:
```
...
    if ($extendSchema = $this->getExtensionDocument($extensions)) {
      // Generate the AST from the extended schema and save it to the cache.
      // This is important, because the Drupal graphql module is not caching the extended schema.
      // During schema extension, a very expensive function \GraphQL\Type\Schema::getTypeMap() is called.
      $document = $this->getExtensionSchemaAST($schema, $extendSchema);
      $options = ['assumeValid' => TRUE];
      $extended_schema = BuildSchema::build($document, function ($config, TypeDefinitionNode $type) use ($resolver) {
        if ($type instanceof InterfaceTypeDefinitionNode || $type instanceof UnionTypeDefinitionNode) {
          $config['resolveType'] = $resolver;
        }
        return $config;
      }, $options);
      return $extended_schema;
    }

...

  public function getExtensionSchemaAST($schema, $extendSchema) {
    $cid = "schema_extension:{$this->getPluginId()}";
    if (empty($this->inDevelopment) && $cache = $this->astCache->get($cid)) {
      return $cache->data;
    }

    $schema = SchemaExtender::extend($schema, $extendSchema);
    $schema_string = SchemaPrinter::doPrint($schema);
    $options = ['noLocation' => TRUE];
    $ast = Parser::parse($schema_string, $options);
    if (empty($this->inDevelopment)) {
      $this->astCache->set($cid, $ast, CacheBackendInterface::CACHE_PERMANENT, ['graphql']);
    }

    return $ast;
  }
```

The first time the schema is extended, we save the resulting AST from the cache. On any subsequent request, we can get the AST from the cache and load it into our `BuildSchema::build()`. This is superfast, because `BuildSchema::build` is lazy-loading our types and is not scanning the whole schema.
See documentation here: https://webonyx.github.io/graphql-php/schema-definition-language/#performance-considerations

This changes will result in a massive performance improvement. In total, we saved more than 400ms on cached each request.

![image](https://user-images.githubusercontent.com/432045/200852014-33bae4d5-35a3-42ef-8d0f-7cca3d306a0b.png)

I will create a pull-request to address this issues.

**Comment by ayalon** [comment] 2022-11-09 15:06
Here is the related pull-request:
https://github.com/drupal-graphql/graphql/pull/1314

**Comment by pfrenssen** [comment] 2022-12-21 13:27
Thanks for creating this issue! I am wondering though if it wouldn't be better to have separate issues and PRs for each of the identified performance problems? It can be more difficult to assess the impact if multiple issues are addressed at once.

**Comment by Kingdutch** [comment] 2023-04-15 12:42
Thanks for the extensive analysis! I agree with pfrenssen that this would be easier to review and assess with PRs for each individually discovered issue.

There has been some previous discussion around caching in #948 and I'd definitely be curious to hear how your changes play with anonymous functions, since we haven't gotten rid of those yet.

Additionally from what I see in your PR right now it appears you disable schema validation completely, rather than only for cached schema's?

**Comment by Sam152** [comment] 2023-05-26 07:44
I did some profiling and found some of the same problems @ayalon found. I applied his PR as a patch wholesale and it halved the time most queries took on my site.

**Comment by Kingdutch** [comment] 2023-07-26 15:03
I hope to take a stab at this in the near future and provide a slightly different method of caching the schema with extensions.

**Comment by klausi** [comment] 2023-11-12 09:26
The `noLocation` hack was committed in #1364.

**Comment by klausi** [comment] 2023-11-12 11:11
I think the simple approach in #1314 makes a lot of sense, thanks! I reworked it a bit in #1379, please test!

@Kingdutch I think this is a good intermediary step before we explore your more sophisticated performance improvements with the AST on disk.

**Comment by klausi** [comment] 2023-11-12 17:54
Initial performance testing in Jobiqo with a lot of schema extensions shows 30-40% full request time improvements, yay! Will do a full test for regressions next.

**Comment by ayalon** [comment] 2023-11-12 18:20
Thanks for looking into this issue. All the improvement I have posted are already part of the graphql_core_schema modules since November 2022. This module is intensively used and tested.
https://www.drupal.org/project/graphql_core_schema

If all the changes, especially the caching of the schema extensions can go back into the main graphql module, we are happy to remove the changes from the graphql_core_schema. Thanks for working on this @klausi .

**Closed as completed** 2023-12-20 12:57 UTC
Labels: performance, 4.x
